Fixed a typo?
`node app` returned:

```
TypeError: Cannot read property 'length' of undefined
   at module.exports (/Users/bobclewell/Code/kimpton/node_modules/apostrophe-multisite/index.js:96:14) 
```

But with this change node app worked. So this fixed it? Seems likely.